language: python
python:
- 3.6
- 3.7
- 3.8
cache: pip
install:
- pip install -U pip setuptools
- pip install .
- pip install pytest pytest-django pytest-pythonpath wagtail-factories
- echo 'hello world!!!!'
script:
- pytest
deploy:
  provider: pypi
  server: $PYPI_URL
  user: "__token__"
  password: $PYPI_TOKEN
  skip_existing: true
  on:
    tags: true
